### ISSUE TITLE
Probably missing ENV variable in restore example in README.md

### ISSUE THREAD

**Issue by gabka913** [ix-ai/mariadb-backup#3]
There is the MODE variable in Environment Variables list, which controls whether it is a backup or restore operation.   
This MODE variable is missing from the restore example command:

```
To restore a backup into a MySQL container via docker CLI client:  
  
docker run --name my-restore -e DB_HOST=mariadb -e DB_PASS=amazing_pass -v /var/mysql_backups:/backup registry.gitlab.com/ix.ai/mariadb-backup:latest
```

**Comment by tlex** [comment]
Thanks for pointing it out. You're right, the `-e MODE=RESTORE` is missing in the example.
